// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jvtzcxlfxrctgkwefzfn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp2dHpjeGxmeHJjdGdrd2VmemZuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI5MDI3MjYsImV4cCI6MjA2ODQ3ODcyNn0.oie5M39A1eMLoOLPPszXXG_FOgu5PnNguj1Cr17lSj0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});